name: End-to-end tests Paralelo
on: [push]
jobs:
  cypress-run-1:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run-1
        uses: cypress-io/github-action@v5
        with:
          command: npm run test:batch-1
  cypress-run-2:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run-2
        uses: cypress-io/github-action@v5
        with:
          command: npm run test:batch-2
  cypress-run-3:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run-3
        uses: cypress-io/github-action@v5
        with:
          command: npm run test:batch-3
  cypress-run-4:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run-4
        uses: cypress-io/github-action@v5
        with:
          command: npm run test:batch-4